"""Step 8: write reports/TECHNICAL_REPORT.md from the saved result files (no number is typed by hand).

    python -m scripts.make_report
"""
import json

import pandas as pd

from src.config import load_config, project_path

MET = project_path("reports/metrics")


def j(name):
    p = MET / name
    return json.loads(p.read_text()) if p.exists() else None


def pc(x):
    return f"{x * 100:.2f}%"


def main():
    cfg = load_config()
    ds, clf, hist = j("dataset_report.json"), j("classifier_test_metrics.json"), j("training_history.json")
    rel, sel, ext = j("reliability_test_metrics.json"), j("reliability_model_selection.json"), j("external_plantdoc_metrics.json")
    rob = pd.read_csv(MET / "robustness_by_corruption.csv")
    cmp_ = pd.read_csv(MET / "reliability_baseline_comparison.csv")
    imp = pd.read_csv(MET / "reliability_feature_importance_B.csv")
    schema = json.loads((project_path("models") / "reliability_schema.json").read_text())
    pv, pdoc = ds["plantvillage"], ds["plantdoc"]

    worst = rob[rob["family"] != "clean"].sort_values("accuracy").iloc[0]
    rf_b, conf = cmp_.set_index("method").loc["Random Forest (B)"], cmp_.set_index("method").loc["Confidence threshold"]
    rf_a = cmp_.set_index("method").loc["Random Forest (A)"]
    m_all = rel["methods"]
    clean_b = m_all["Random Forest (B)"]["clean only"]
    clean_cmp = "; ".join(f"{name} PR-AUC {v['clean only']['pr_auc']:.3f}, recall {pc(v['clean only']['recall'])}, false alarms "
                          f"{pc(v['clean only']['false_alarm_rate'])}" for name, v in m_all.items())
    clean_best = max(m_all, key=lambda n: m_all[n]["clean only"]["pr_auc"])

    def rob_table():
        d = rob.copy()
        d["accuracy"] = d["accuracy"].map(pc)
        d["macro_f1"] = d["macro_f1"].map(lambda v: f"{v:.4f}")
        d["prediction_change_rate"] = d["prediction_change_rate"].map(pc)
        return d[["family", "severity", "value", "images", "accuracy", "macro_f1", "prediction_change_rate"]].to_markdown(index=False)

    def cmp_table():
        d = cmp_.copy()
        for c in ("precision", "recall", "f1", "false_negative_rate", "false_alarm_rate", "flagged_share"):
            d[c] = d[c].map(pc)
        for c in ("roc_auc", "pr_auc", "aurc"):
            d[c] = d[c].map(lambda v: f"{v:.4f}")
        return d.to_markdown(index=False)

    s_ext = ext["strict_exact_mappings"] if ext else None
    text = f"""# AgriShield — Technical Report

*Reliability-Aware Plant Disease Detection Under Image Quality Degradation.* Generated by `scripts/make_report.py` from
`reports/metrics/`. Seed {cfg['seed']}. Every number below is read from those files.

## 1. Problem statement
Plant-disease classifiers trained on curated photos can be wrong without warning when an image is dark, blurred, noisy, compressed
or low-resolution. We measure how much these degradations hurt an EfficientNet-B0 classifier, and test whether a Random Forest
can flag likely-incorrect predictions better than simple confidence or margin thresholds.

## 2. Proposed contribution
An engineering and evaluation study, not a new algorithm:
- a leakage-aware pipeline with separate train / validation / calibration / test partitions;
- a controlled degradation benchmark (6 corruption types × 3 severities);
- a learned error detector (Random Forest) with two deployable feature sets, compared with confidence and margin baselines on
  the same locked test set;
- an external check on PlantDoc.

No literature review was carried out for this deliverable, so **no novelty is claimed**.

## 3. Dataset
**PlantVillage** ({pv['source']}): {pv['files']:,} files, {pv['classes']} classes, {pv['unreadable']} unreadable.
Class sizes are imbalanced, with the largest class {pv['imbalance_ratio_max_over_min']:.1f}× the smallest. The most common image size
is {list(pv['image_sizes_top'])[0]}.

**Duplicates.** {pv['duplicates']['exact_duplicate_pairs']} exact-duplicate pairs (MD5) and {pv['duplicates']['near_duplicate_pairs']}
near-duplicate pairs (dHash ≤ 4 bits) were found. They form {pv['duplicates']['duplicate_groups_with_2plus_images']} multi-image groups.
{pv['duplicates']['images_in_label_conflict_groups_excluded']} images whose duplicates carried a different label were excluded.

**Split.** {pv['split_method']}. Seed {pv['split_seed']}. Sizes: {', '.join(f"{k} {v:,}" for k, v in pv['split_sizes'].items())}.
The calibration images are divided by group into {', '.join(f"{k} {v:,}" for k, v in pv['reliability_roles'].items())}.
Manifests: `reports/manifests/`.

**PlantDoc** ({pdoc['source']}): {pdoc['files']:,} files, {pdoc['classes']} classes. Mapping status:
{', '.join(f"{k} {v:,}" for k, v in pdoc['mapping_status_counts'].items())}. Files byte-identical to PlantVillage:
{pdoc['identical_to_plantvillage_files']}. The label mapping is in `src/external_mapping.py`.

## 4. Methodology
1. Duplicate-aware, class-stratified group split. The test set is locked.
2. Fine-tune EfficientNet-B0 on **train**. Select the epoch with the best **validation** macro-F1.
3. Run the frozen classifier on **calibration** and **test** images, each under 19 conditions (clean + 18 corruptions).
4. Fit the Random Forest on **rel_train**. Choose its hyper-parameters (PR-AUC) and every threshold (max F2) on **rel_val**.
5. Evaluate once on **test**, then on PlantDoc.

## 5. Model architecture
- **Classifier:** torchvision EfficientNet-B0, ImageNet-initialised, with the final layer replaced by Linear(1280, {clf['num_classes']}).
  It has {clf['parameters']:,} parameters, a {clf['model_file_mb']:.1f} MB checkpoint and single-image latency
  {', '.join(f"{k} {v:.1f} ms" for k, v in clf['single_image_latency_ms'].items())}.
- **Training:** AdamW (lr {cfg['training']['learning_rate']}), cosine schedule, batch {cfg['training']['batch_size']},
  class-weighted cross-entropy (1/√frequency), mild augmentation (crop, flip, ±15° rotation, slight colour jitter).
  Training ran for {len(hist['history'])} epochs and the best epoch was {hist['best_epoch']}, on device {hist['device']}.
- **Reliability:** scikit-learn RandomForestClassifier with class_weight="balanced_subsample".
  Selected hyper-parameters: A `{json.dumps(schema['configs']['A']['hyperparameters'])}`, B `{json.dumps(schema['configs']['B']['hyperparameters'])}`.

## 6. Reliability target and features
Target: **1 = the disease prediction is incorrect**, 0 = correct. The ground truth is used only to build this target.
- **Configuration A** ({len(schema['configs']['A']['features'])} features), computed from the uploaded image alone:
  {', '.join(schema['configs']['A']['features'])}.
- **Configuration B** adds stability under a fixed policy of {len(cfg['stability_policy'])} mild perturbations
  (+{len(cfg['stability_policy'])} forward passes per image, applied identically in training and in the app):
  {', '.join(f for f in schema['configs']['B']['features'] if f.startswith('stability'))}.

## 7. Experimental setup
Corruptions are applied to the 256-px image before preprocessing: {json.dumps(cfg['perturbations'])}. Test rows: {rel['test_rows']:,}
({rel['test_images']:,} images × {rel['conditions_per_image']} conditions). Validation-selected thresholds:
RF-A {schema['configs']['A']['threshold']:.4f}, RF-B {schema['configs']['B']['threshold']:.4f}.

## 8. Results
### 8.1 Clean test set (PlantVillage)
| Metric | Value |
|---|---|
| Test images | {clf['test_images']:,} |
| Accuracy | {pc(clf['accuracy'])} |
| Macro precision | {clf['macro_precision']:.4f} |
| Macro recall | {clf['macro_recall']:.4f} |
| Macro F1 | {clf['macro_f1']:.4f} |

The per-class results are in `test_per_class_metrics.csv` and the confusion matrix in `figures/confusion_matrix_test.png`.

### 8.2 Degraded images (same test images)
{rob_table()}

The largest drop was **{worst['family']} at severity {int(worst['severity'])}**, with accuracy {pc(worst['accuracy'])}.

### 8.3 Reliability (positive = incorrect; all {rel['test_rows']:,} test rows)
{cmp_table()}

On **clean images only**, RF-B scored precision {pc(clean_b['precision'])}, recall {pc(clean_b['recall'])} and PR-AUC
{clean_b['pr_auc'] if clean_b['pr_auc'] is not None else float('nan'):.4f}, on {clean_b['n']:,} rows of which {pc(clean_b['incorrect_rate'])} were incorrect.

Clean-only comparison (all methods, same {clean_b['n']:,} rows): {clean_cmp}.
With so few clean errors these numbers are unstable. They should not be read as a ranking.

Calibration of the RF-B score: Brier {rel['calibration_B']['brier']:.4f} (see `figures/reliability_risk_coverage_calibration.png`).

Most important RF-B features (permutation importance on rel_val):
{', '.join(f"{r.feature} ({r.permutation_importance_pr_auc:.4f})" for r in imp.head(5).itertuples())}.

**Answer to the primary question (measured).** On the test rows, RF-B reached PR-AUC {rf_b['pr_auc']:.4f} against
{conf['pr_auc']:.4f} for the confidence threshold. At the validation-chosen thresholds, it had recall {pc(rf_b['recall'])} and
precision {pc(rf_b['precision'])}, against {pc(conf['recall'])} and {pc(conf['precision'])} for the baseline.
RF-A (no extra forward passes) reached PR-AUC {rf_a['pr_auc']:.4f}. On clean images alone, the highest PR-AUC came from
**{clean_best}**, so the Random Forest's advantage comes from the degraded images.
"""
    if s_ext:
        x = ext["extended_with_ambiguous"]
        text += f"""
### 8.4 External test (PlantDoc, reported separately)
- **Strict mappings:** {s_ext['images']:,} images, {s_ext['classes']} classes. Accuracy {pc(s_ext['accuracy'])},
  top-3 {pc(s_ext['top3_accuracy'])}, macro-F1 {s_ext['macro_f1_over_present_classes']:.4f}.
- **Extended mappings:** {x['images']:,} images. Accuracy {pc(x['accuracy'])}.
- Excluded: {json.dumps(ext['excluded'])}. Evaluation failures: {len(ext['failures'])}.
"""
        if "reliability_B" in s_ext:
            r = s_ext["reliability_B"]
            ra = s_ext["reliability_A"]
            text += (f"- Reliability on PlantDoc (strict): {pc(r['incorrect_rate'])} of predictions were incorrect.\n"
                     f"  - RF-B: recall {pc(r['recall'])}, precision {pc(r['precision'])}, ROC-AUC {r['roc_auc']:.3f}, PR-AUC "
                     f"{r['pr_auc']:.3f}, flagged {pc(r['flagged_share'])}.\n"
                     f"  - RF-A: ROC-AUC {ra['roc_auc']:.3f}, PR-AUC {ra['pr_auc']:.3f}.\n"
                     f"  - The high PR-AUC mostly reflects the high error rate. A random score would reach about "
                     f"{r['incorrect_rate']:.2f}. The ROC-AUC values show that on field photos the reliability model separates "
                     f"correct from incorrect predictions much less well than on PlantVillage.\n")
    text += """
## 9. Limitations
- PlantVillage images are lab-style: a single leaf on a plain background. High internal accuracy does not mean field performance;
  see the external PlantDoc results.
- The degradations are synthetic. Real field problems such as occlusion, several leaves, shadows or a different camera are only
  partly represented.
- The Random Forest learns PlantVillage-style errors. Its risk score is a learned score; calibration was measured only on PlantVillage
  test rows.
- Each test image appears under 19 conditions, so the reliability rows are not independent samples.
- There was a single training run with one seed, so no confidence intervals are reported.
- No literature review was performed, so no novelty or superiority over published methods is claimed.

## 10. Future improvements
- Train or fine-tune with field images, and evaluate on more PlantDoc-style data.
- Run repeated seeds and report confidence intervals; add statistical tests between the reliability methods.
- Recalibrate the risk score (isotonic or Platt) on rel_val, and add conformal prediction for coverage guarantees.
- Add segmentation or leaf detection for multi-leaf field photos.
"""
    (project_path("reports") / "TECHNICAL_REPORT.md").write_text(text, encoding="utf-8")
    print("wrote reports/TECHNICAL_REPORT.md")


if __name__ == "__main__":
    main()
